version: "1.0"
services:
  productpage:
    build: ProductPage/
    ports:
      - "9080:9080"
    links:
      - details
      - reviews
  details:
    build: Details/
  reviews:

    image: reviews
    environment:
          - service_version=v3
          - enable_ratings=true
          - star_color=red
    links:
      - ratings
  ratings:
      build: Ratings/